# Generated by Django 3.2.7 on 2021-09-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='date_created',
        ),
    ]
